/**
 * Audio engine + audio-reactive data — TWO pipelines behind ONE API.
 *
 *   LIVE_WEB_AUDIO   (desktop): the original, UNCHANGED engine. ONE AudioContext,
 *     ONE GainNode (0.6), ONE AnalyserNode. The MP3 is decoded once into an
 *     AudioBuffer with a ~12ms baked head-tail crossfade and looped through an
 *     AudioBufferSourceNode (sample-accurate, gapless). The analyser feeds
 *     bass/mid/high + the spectral heatmap.
 *
 *   PRECOMPUTED_MOBILE (iPhone/iPad/touch): playback is a PLAIN HTMLAudioElement
 *     — NEVER routed through createMediaElementSource()/AudioContext — so it
 *     stays on iOS's media channel and is audible even with the mute switch ON.
 *     Because that element can't be analysed without pulling it back onto the
 *     (muteable) Web Audio session, the Sonic Pulse + heatmap are driven by an
 *     OFFLINE spectral asset (public/audio/intruder-spectrum.bin, generated by
 *     scripts/generate-audio-analysis.mjs) sampled by `audio.currentTime` and
 *     interpolated between the two adjacent frames. No AudioContext is created.
 *
 * The mode is decided ONCE per session (device, not viewport) so a mid-session
 * resize can never spawn a second audible source. Everything downstream
 * (getBands/getEnv/getHeatmap/tick) is identical for both modes.
 */
import { EFFECTS, HEATMAP, PULSE, telemetry } from "./effectsConfig";

const AUDIO_URL = "/audio/intruder-snippet.mp3";
const SPECTRUM_BIN_URL = "/audio/intruder-spectrum.bin";
const SPECTRUM_META_URL = "/audio/intruder-spectrum-meta.json";
const CROSSFADE_MS = 12; // baked head-tail crossfade to kill the junction click
const VOLUME = 0.6; // fixed base volume (unchanged, both modes)
const FADE_S = 0.008; // pause/resume click-guard fade

export type AudioMode = "LIVE_WEB_AUDIO" | "PRECOMPUTED_MOBILE";

// The mode is resolved ONCE and cached — never re-evaluated on resize, so a
// viewport change during the session can't switch engines / duplicate audio.
let MODE: AudioMode | null = null;
function detectMode(): AudioMode {
  if (typeof window === "undefined" || typeof navigator === "undefined")
    return "LIVE_WEB_AUDIO";
  const ua = navigator.userAgent || "";
  const isIOS =
    /iP(hone|od|ad)/.test(ua) ||
    (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1); // iPadOS 13+
  const isTouch =
    "ontouchstart" in window || navigator.maxTouchPoints > 0;
  // Touch/iOS -> precomputed mobile pipeline. A non-touch desktop stays on the
  // LIVE Web Audio engine at ANY width (desktop invariato — a narrow window
  // never flips the engine).
  return isIOS || isTouch ? "PRECOMPUTED_MOBILE" : "LIVE_WEB_AUDIO";
}
export function audioMode(): AudioMode {
  if (!MODE) {
    MODE = detectMode();
    telemetry.mode = MODE;
  }
  return MODE;
}

type Graph = {
  ctx: AudioContext;
  gain: GainNode;
  analyser: AnalyserNode;
  hp: BiquadFilterNode; // MIXER high-pass (desktop) — neutral until swept
  lp: BiquadFilterNode; // MIXER low-pass  (desktop) — neutral until swept
  fx: HeatFx; // scroll-driven Heat FX stage (post-analyser; dry at heat=0)
  freq: Uint8Array<ArrayBuffer>;
  buffer: AudioBuffer | null; // seamless loop buffer (null until decoded)
  source: AudioBufferSourceNode | null; // the ONE playing source (or null)
  loopDuration: number; // seconds
};

// The Heat FX stage's automatable wet sends + fixed nodes. Created ONCE with the
// graph and never recreated; only the three wet GainNodes move (scaled by the Home
// scroll heat), so scrolling issues no node churn.
type HeatFx = {
  input: GainNode; // stage tap (analyser → input)
  dry: GainNode; // constant unity pass-through (the untouched playback)
  delay: DelayNode;
  delayFb: GainNode; // bounded feedback (< 1, always decays)
  delayWet: GainNode; // 0 → HEAT_DELAY_WET
  convolver: ConvolverNode;
  revWet: GainNode; // 0 → HEAT_REVERB_WET
  shaper: WaveShaperNode;
  satMakeup: GainNode;
  satWet: GainNode; // 0 → HEAT_SAT_WET
  output: GainNode; // sums dry + wet → destination
};

// --- MIXER filter sweep (desktop) -------------------------------------------
// Two BiquadFilterNodes inserted between the source and the gain, so the shared
// analyser (and therefore the waveform) sees the FILTERED signal. Amounts are a
// normalized 0..1 (0 = neutral / inaudible). Log-mapped to musical corner
// frequencies; smoothly automated with setTargetAtTime (no zipper/clicks).
const HP_FREQ_MIN = 20; // HP amount 0 → 20Hz (below audible → passes everything)
const HP_FREQ_MAX = 6000; // HP amount 1 → 6kHz (removes lows)
const LP_FREQ_MAX = 20000; // LP amount 0 → 20kHz (above audible → passes everything)
const LP_FREQ_MIN = 300; // LP amount 1 → 300Hz (removes highs)
const FILTER_TAU = 0.03; // AudioParam smoothing time-constant (s)
let hpAmount = 0; // persisted so a value set before the graph exists still applies
let lpAmount = 0;
const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);

// --- HEAT FX (desktop) ------------------------------------------------------
// A restrained, scroll-driven warmth/space stage placed AFTER the analyser, so
// HP/LP, the waveform and the dry sound are untouched (the analyser sees the same
// pre-Heat signal). Three PARALLEL wet sends (short delay, light reverb, warm
// saturation) blend beside a constant unity dry path — the dry playback is never
// altered, and at heat=0 every wet send is silent → bit-transparent. All wet
// amounts scale 0→max by the authoritative Home scroll heat (telemetry.heat), and
// only while HOME is mounted (heatEnabled) AND music is playing. Values sit inside
// the approved guardrails; automation is setTargetAtTime (zipper-free).
const HEAT_DELAY_S = 0.07; // 70ms slapback (guardrail 50–90ms)
const HEAT_DELAY_FB = 0.28; // bounded feedback — subtle repeats, always < 1 (decays)
const HEAT_DELAY_WET = 0.05; // max delay wet send (guardrail ~4–6%)
const HEAT_REVERB_S = 0.4; // short synthetic impulse (light room)
const HEAT_REVERB_DECAY = 3.0; // impulse decay exponent
const HEAT_REVERB_WET = 0.08; // max reverb wet send (guardrail ~6–10%)
const HEAT_SAT_K = 2.0; // tanh(k·x)/k → unity small-signal slope, gentle peak soft-clip
const HEAT_SAT_MAKEUP = 1.3; // light comp so the peak-compressed copy reads ~unity
const HEAT_SAT_WET = 0.06; // max saturation wet send (guardrail ~5–8%)
const HEAT_TAU = 0.1; // wet-gain automation smoothing (s) — no clicks/zipper
let heatEnabled = false; // Home gate (set by the Home cue on mount/unmount)
let heatSuppressed = false; // future Scratch hook — inert until explicitly activated

// --- LIVE_WEB_AUDIO state (desktop) -----------------------------------------
let graph: Graph | null = null;
let decoding = false;
let pendingArrayBuffer: ArrayBuffer | null = null; // prefetched MP3 bytes (mount)
let prefetching = false;
let resumeOffset = 0; // musical offset (s) to (re)start from
let srcStartCtxTime = 0; // ctx.currentTime when the current source started
let srcStartOffset = 0; // offset the current source started at
let wantPlay = false; // the app's desired state (should audio be playing?)
let autoplayOnce = true; // one-shot autoplay attempt at load (after decode)
let unlocked = false; // iOS Web Audio unlocked (silent buffer played in a gesture)

// --- PRECOMPUTED_MOBILE state (HTMLAudioElement + offline spectrum) ----------
let mediaEl: HTMLAudioElement | null = null;
let spectrum: Uint8Array | null = null; // flat Uint8: frames × frameStride
type SpectrumMeta = {
  analysisFps: number;
  bandCount: number;
  frameStride: number;
  frames: number;
  durationSec: number;
  layout: {
    bands: [number, number];
    bass: number;
    mid: number;
    high: number;
    rms: number;
    peak: number;
  };
};
let spectrumMeta: SpectrumMeta | null = null;
let spectrumLoading = false;
// Interpolated current-frame values (reused, never allocated per frame).
const mBands = new Float32Array(HEATMAP.numBands);
const mBMH = { bass: 0, mid: 0, high: 0, rms: 0, peak: 0 };

// --- shared play-state ------------------------------------------------------
const playListeners = new Set<(p: boolean) => void>();
let playingTarget = false; // desired state (real playback)
let env = 0; // 0..1 fade envelope (in on play, out on pause)
const bands = { bass: 0, mid: 0, high: 0 }; // smoothed (curved/normalized), pre-envelope
const peaks = { bass: PULSE.peakFloor, mid: PULSE.peakFloor, high: PULSE.peakFloor };

// --- Spectral heatmap: all arrays reused, never allocated in the loop --------
const HM_N = HEATMAP.numBands;
const hmSmooth = new Float32Array(HM_N); // temporally smoothed per-band energy (0..1)
const hmRaw = new Float32Array(HM_N); // raw band energy scratch (reused each frame)
const hmField = new Float32Array(HM_N); // spatially blurred output (getHeatmap)
let hmNorm = HEATMAP.normFloor; // adaptive normalization peak
let externalDriver = false; // true while the Monogram loop drives tick()
let internalRaf = 0;
let internalLast = 0;
let visibilityHooked = false;

const isMobile = () =>
  typeof window !== "undefined" && window.innerWidth <= 767;

/** Bake a seamless loop: crossfade the tail into the head once, so the source's
 *  loop wrap (last sample -> first) is continuous and the junction never clicks.
 *  Sacrifices the final CROSSFADE_MS as blend material only. */
function makeSeamlessLoop(ctx: BaseAudioContext, src: AudioBuffer): AudioBuffer {
  const sr = src.sampleRate;
  const ch = src.numberOfChannels;
  const L = Math.min(Math.round((sr * CROSSFADE_MS) / 1000), src.length >> 2);
  const M = src.length - L; // loop length
  const out = ctx.createBuffer(ch, M, sr);
  for (let c = 0; c < ch; c++) {
    const s = src.getChannelData(c);
    const d = out.getChannelData(c);
    for (let i = L; i < M; i++) d[i] = s[i]; // bulk
    // head[0..L) = equal-power blend of tail (fading out) into head (fading in);
    // d[0] = tail start (=s[M]) so d[M-1](=s[M-1]) -> d[0](=s[M]) is continuous.
    for (let i = 0; i < L; i++) {
      const w = (i + 0.5) / L; // 0..1
      const wi = Math.sin((w * Math.PI) / 2); // head gain
      const wo = Math.cos((w * Math.PI) / 2); // tail gain
      d[i] = s[i] * wi + s[M + i] * wo;
    }
  }
  return out;
}

// --- HEAT FX builders -------------------------------------------------------
/** Short, light synthetic reverb impulse: exponentially-decaying stereo noise. */
function makeHeatImpulse(
  ctx: BaseAudioContext,
  seconds: number,
  decay: number,
): AudioBuffer {
  const rate = ctx.sampleRate;
  const len = Math.max(1, Math.floor(rate * seconds));
  const buf = ctx.createBuffer(2, len, rate);
  for (let ch = 0; ch < 2; ch++) {
    const d = buf.getChannelData(ch);
    for (let i = 0; i < len; i++) {
      d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, decay);
    }
  }
  return buf;
}

/** Warm saturation curve = tanh(k·x)/k: unity slope at 0 (small signals pass
 *  through untouched) with a gentle symmetric soft-clip on peaks → warm odd
 *  harmonics, and NO small-signal level increase. */
function makeSatCurve(k: number): Float32Array<ArrayBuffer> {
  const n = 1024;
  const c = new Float32Array(new ArrayBuffer(n * 4)); // <ArrayBuffer> for WaveShaper.curve
  for (let i = 0; i < n; i++) {
    const x = (i / (n - 1)) * 2 - 1;
    // tanh(k·x)/k → slope 1 at x=0 (small signals unchanged), soft-clipped peaks.
    c[i] = Math.tanh(k * x) / k;
  }
  return c;
}

/** Build the post-analyser Heat FX stage. Dry is a constant unity path; the three
 *  wet sends start silent (0) and are opened by updateHeat(). Returns the handles
 *  updateHeat automates. Graph: source → hp → lp → gain → analyser → INPUT →
 *  (dry ‖ delay ‖ reverb ‖ saturation) → OUTPUT → destination. */
function buildHeatFx(ctx: AudioContext, tap: AudioNode): HeatFx {
  const input = ctx.createGain();
  input.gain.value = 1;
  const output = ctx.createGain();
  output.gain.value = 1;
  const dry = ctx.createGain();
  dry.gain.value = 1;

  const delay = ctx.createDelay(0.5);
  delay.delayTime.value = HEAT_DELAY_S;
  const delayFb = ctx.createGain();
  delayFb.gain.value = HEAT_DELAY_FB;
  const delayWet = ctx.createGain();
  delayWet.gain.value = 0;

  const convolver = ctx.createConvolver();
  convolver.normalize = true;
  convolver.buffer = makeHeatImpulse(ctx, HEAT_REVERB_S, HEAT_REVERB_DECAY);
  const revWet = ctx.createGain();
  revWet.gain.value = 0;

  const shaper = ctx.createWaveShaper();
  shaper.curve = makeSatCurve(HEAT_SAT_K);
  shaper.oversample = "2x";
  const satMakeup = ctx.createGain();
  satMakeup.gain.value = HEAT_SAT_MAKEUP;
  const satWet = ctx.createGain();
  satWet.gain.value = 0;

  // Dry (unity, bit-transparent) — the untouched playback.
  tap.connect(input);
  input.connect(dry);
  dry.connect(output);
  // Delay send with bounded internal feedback (subtle slapback).
  input.connect(delay);
  delay.connect(delayFb);
  delayFb.connect(delay);
  delay.connect(delayWet);
  delayWet.connect(output);
  // Reverb send (short light room).
  input.connect(convolver);
  convolver.connect(revWet);
  revWet.connect(output);
  // Parallel warm saturation send.
  input.connect(shaper);
  shaper.connect(satMakeup);
  satMakeup.connect(satWet);
  satWet.connect(output);

  output.connect(ctx.destination);
  return {
    input,
    dry,
    delay,
    delayFb,
    delayWet,
    convolver,
    revWet,
    shaper,
    satMakeup,
    satWet,
    output,
  };
}

/** Per-frame Heat automation (LIVE/desktop only). Opens the three wet sends toward
 *  their guarded maxima scaled by the authoritative Home scroll heat — but only
 *  while HOME is mounted, not suppressed (future Scratch), and music is running;
 *  otherwise it ramps every send back to fully dry. All moves are setTargetAtTime
 *  (zipper-free); no nodes are created/destroyed. */
function updateHeat(running: boolean): void {
  if (!graph) return;
  const fx = graph.fx;
  const on = heatEnabled && !heatSuppressed && running;
  const h = on ? clamp01(telemetry.heat) : 0;
  const t = graph.ctx.currentTime;
  fx.delayWet.gain.setTargetAtTime(HEAT_DELAY_WET * h, t, HEAT_TAU);
  fx.revWet.gain.setTargetAtTime(HEAT_REVERB_WET * h, t, HEAT_TAU);
  fx.satWet.gain.setTargetAtTime(HEAT_SAT_WET * h, t, HEAT_TAU);
}

// ============================================================================
//  PRECOMPUTED_MOBILE — HTMLAudioElement (media channel) + offline spectrum
// ============================================================================

/** The single mobile <audio>. Deliberately NOT connected to any AudioContext —
 *  that keeps it on iOS's media channel (audible with the mute switch ON). */
function ensureMediaEl(): HTMLAudioElement | null {
  if (mediaEl) return mediaEl;
  if (typeof Audio === "undefined") return null;
  const el = new Audio();
  el.src = AUDIO_URL;
  el.loop = true; // native gapless-enough loop (the visual loop uses currentTime % dur)
  el.volume = VOLUME; // fixed 0.6
  el.preload = "auto";
  el.setAttribute("playsinline", "");
  (el as HTMLAudioElement & { playsInline?: boolean }).playsInline = true;
  el.addEventListener("play", () => notifyPlaying(true));
  el.addEventListener("playing", () => notifyPlaying(true));
  el.addEventListener("pause", () => notifyPlaying(false));
  el.addEventListener("ended", () => notifyPlaying(false));
  mediaEl = el;
  return el;
}

/** Load the compact offline spectral asset once (meta then bin). No AudioContext. */
function loadSpectrum(): void {
  if (spectrum || spectrumLoading || typeof fetch === "undefined") return;
  spectrumLoading = true;
  fetch(SPECTRUM_META_URL)
    .then((r) => r.json() as Promise<SpectrumMeta>)
    .then((meta) => {
      spectrumMeta = meta;
      telemetry.analysisFps = meta.analysisFps;
      return fetch(SPECTRUM_BIN_URL).then((r) => r.arrayBuffer());
    })
    .then((buf) => {
      spectrum = new Uint8Array(buf);
      telemetry.analysisLoaded = true;
    })
    .catch(() => {
      spectrumLoading = false;
    });
}

/** Sample the offline spectrum at the media element's current playback time,
 *  interpolating between the two adjacent analysis frames (loops via
 *  currentTime % duration). Fills mBands[] + mBMH; returns whether audio is
 *  actually playing. Zero per-frame allocation. */
function sampleMobile(): boolean {
  const el = mediaEl;
  const spec = spectrum;
  if (!el || !spec || !spectrumMeta) return false;
  const running = !el.paused && !el.ended && el.readyState >= 2;
  if (!running) return false;
  const { analysisFps, frames, frameStride, durationSec, bandCount, layout } =
    spectrumMeta;
  const dur = durationSec > 0 ? durationSec : frames / analysisFps;
  let ct = el.currentTime;
  if (!(ct >= 0)) ct = 0;
  const pos = ct % dur; // seamless visual loop
  const vf = pos * analysisFps; // fractional frame
  let ia = Math.floor(vf);
  const mix = vf - ia;
  if (ia >= frames) ia = frames - 1;
  let ib = ia + 1;
  if (ib >= frames) ib = 0; // wrap to the loop start (no jump at the seam)
  const baseA = ia * frameStride;
  const baseB = ib * frameStride;
  const n = Math.min(HM_N, bandCount);
  for (let i = 0; i < n; i++) {
    const a = spec[baseA + i];
    const b = spec[baseB + i];
    mBands[i] = (a + (b - a) * mix) / 255;
  }
  const at = (off: number) => {
    const a = spec[baseA + off];
    const b = spec[baseB + off];
    return (a + (b - a) * mix) / 255;
  };
  mBMH.bass = at(layout.bass);
  mBMH.mid = at(layout.mid);
  mBMH.high = at(layout.high);
  mBMH.rms = at(layout.rms);
  mBMH.peak = at(layout.peak);
  telemetry.analysisFrame = ia;
  return true;
}

// ============================================================================
//  LIVE_WEB_AUDIO — the original desktop engine (UNCHANGED behaviour)
// ============================================================================

/** Create the single audio graph + start decoding the loop (idempotent). */
function ensureLiveGraph(): boolean {
  if (graph) return true;
  const AC: typeof AudioContext =
    window.AudioContext ||
    (window as unknown as { webkitAudioContext: typeof AudioContext })
      .webkitAudioContext;
  if (!AC) return false;
  let ctx: AudioContext;
  try {
    ctx = new AC();
  } catch {
    return false;
  }
  const gain = ctx.createGain();
  gain.gain.value = VOLUME;
  const analyser = ctx.createAnalyser();
  analyser.fftSize = isMobile() ? PULSE.fftSizeMobile : PULSE.fftSizeDesktop;
  analyser.smoothingTimeConstant = PULSE.smoothing;
  // MIXER filters, inserted BEFORE the gain/analyser so the waveform reacts to the
  // filtered signal: source → hp → lp → gain → analyser → destination. Both start
  // neutral (HP low, LP high) and are restored to the current amounts below.
  const hp = ctx.createBiquadFilter();
  hp.type = "highpass";
  hp.frequency.value = HP_FREQ_MIN;
  hp.Q.value = 0.707;
  const lp = ctx.createBiquadFilter();
  lp.type = "lowpass";
  lp.frequency.value = LP_FREQ_MAX;
  lp.Q.value = 0.707;
  hp.connect(lp);
  lp.connect(gain);
  gain.connect(analyser);
  // Heat FX stage inserted AFTER the analyser: the waveform + HP/LP see the same
  // pre-Heat signal, and at heat=0 the dry path is bit-transparent to destination.
  const fx = buildHeatFx(ctx, analyser);
  graph = {
    ctx,
    gain,
    analyser,
    hp,
    lp,
    fx,
    freq: new Uint8Array(new ArrayBuffer(analyser.frequencyBinCount)),
    buffer: null,
    source: null,
    loopDuration: 0,
  };
  // Re-apply any amounts set before the graph was built (jump, no ramp needed).
  applyHp(hpAmount, true);
  applyLp(lpAmount, true);
  if (!visibilityHooked) {
    visibilityHooked = true;
    document.addEventListener("visibilitychange", () => {
      if (document.hidden) zeroOut();
      else if (graph && graph.source && graph.ctx.state === "suspended")
        graph.ctx.resume().catch(() => {}); // resume playback returning to fg
    });
  }
  // Decode the loop once, off the audio thread. Reuse the MP3 bytes prefetched
  // at mount (no download wait on the first tap); fall back to fetching now.
  // Use the CALLBACK form of decodeAudioData wrapped in a Promise — the promise
  // form is unreliable on older iOS Safari / webkitAudioContext.
  if (!decoding) {
    decoding = true;
    const bytes: Promise<ArrayBuffer> = pendingArrayBuffer
      ? Promise.resolve(pendingArrayBuffer)
      : fetch(AUDIO_URL).then((r) => r.arrayBuffer());
    bytes
      .then(
        (a) =>
          new Promise<AudioBuffer>((resolve, reject) => {
            ctx.decodeAudioData(a, resolve, reject);
          }),
      )
      .then((decoded) => {
        if (!graph) return;
        graph.buffer = makeSeamlessLoop(ctx, decoded);
        graph.loopDuration = graph.buffer.length / graph.buffer.sampleRate;
        telemetry.loopStart = 0;
        telemetry.loopEnd = graph.loopDuration;
        telemetry.loopDuration = graph.loopDuration;
        if (autoplayOnce) {
          autoplayOnce = false;
          graph.ctx
            .resume()
            .then(() => {
              if (graph && graph.ctx.state === "running" && !unlocked) {
                wantPlay = true;
                reconcile();
              }
            })
            .catch(() => {});
        } else {
          reconcile(); // a toggle before decode set the desired state
        }
      })
      .catch(() => {
        decoding = false;
      });
  }
  return true;
}

/** Current musical offset (seconds) within the seamless loop. */
function currentOffset(): number {
  if (!graph || !graph.source) return resumeOffset;
  const elapsed = graph.ctx.currentTime - srcStartCtxTime;
  return (srcStartOffset + elapsed) % graph.loopDuration;
}

/** Create a fresh looping source at `offset` with a tiny fade-in. */
function startSource(offset: number): void {
  if (!graph || !graph.buffer || graph.source) return;
  const { ctx, gain, buffer } = graph;
  const src = ctx.createBufferSource();
  src.buffer = buffer;
  src.loop = true;
  src.loopStart = 0;
  src.loopEnd = graph.loopDuration;
  src.connect(graph.hp); // → hp → lp → gain → analyser → destination
  const t = ctx.currentTime;
  gain.gain.cancelScheduledValues(t);
  gain.gain.setValueAtTime(0.0001, t);
  gain.gain.linearRampToValueAtTime(VOLUME, t + FADE_S);
  src.start(t, offset % graph.loopDuration);
  srcStartCtxTime = t;
  srcStartOffset = offset % graph.loopDuration;
  graph.source = src;
  notifyPlaying(true);
}

/** Stop the source keeping the musical position (short fade -> no click). */
function stopSource(): void {
  if (!graph || !graph.source) return;
  resumeOffset = currentOffset();
  const { ctx, gain } = graph;
  const s = graph.source;
  graph.source = null;
  const t = ctx.currentTime;
  gain.gain.cancelScheduledValues(t);
  gain.gain.setValueAtTime(gain.gain.value, t);
  gain.gain.linearRampToValueAtTime(0.0001, t + FADE_S);
  try {
    s.stop(t + FADE_S + 0.005);
  } catch {
    /* ignore */
  }
  s.onended = () => {
    try {
      s.disconnect();
    } catch {
      /* ignore */
    }
  };
  notifyPlaying(false);
}

/** iOS Safari unlock (LIVE mode only): resume + start a 1-sample silent buffer
 *  SYNCHRONOUSLY in the gesture so a later real source start plays normally. */
function unlock(): void {
  if (!graph) return;
  graph.ctx.resume().catch(() => {});
  if (unlocked) return;
  try {
    const b = graph.ctx.createBuffer(1, 1, graph.ctx.sampleRate);
    const s = graph.ctx.createBufferSource();
    s.buffer = b;
    s.connect(graph.ctx.destination);
    s.start(0);
    s.onended = () => {
      try {
        s.disconnect();
      } catch {
        /* ignore */
      }
    };
    unlocked = true;
  } catch {
    /* ignore */
  }
}

/** Bring actual playback in line with the desired state `wantPlay` (LIVE). */
function reconcile(): void {
  if (!graph || !graph.buffer) return;
  if (wantPlay && !graph.source) startSource(resumeOffset);
  else if (!wantPlay && graph.source) stopSource();
}

// ============================================================================
//  PUBLIC API — dispatches to the active mode
// ============================================================================

/** Create/prepare the active engine (idempotent). */
export function ensureAudio(): boolean {
  if (audioMode() === "PRECOMPUTED_MOBILE") {
    ensureMediaEl();
    loadSpectrum();
    return true;
  }
  return ensureLiveGraph();
}

/** Prefetch playback assets at mount WITHOUT creating an AudioContext.
 *  LIVE: fetch the MP3 bytes (context is built later, in-gesture on iOS).
 *  MOBILE: create the <audio> (preload=auto downloads it) + load the spectrum. */
export function prefetchAudio(): void {
  if (audioMode() === "PRECOMPUTED_MOBILE") {
    ensureMediaEl();
    loadSpectrum();
    return;
  }
  if (prefetching || pendingArrayBuffer || typeof fetch === "undefined") return;
  prefetching = true;
  fetch(AUDIO_URL)
    .then((r) => r.arrayBuffer())
    .then((a) => {
      pendingArrayBuffer = a;
    })
    .catch(() => {
      prefetching = false;
    });
}

/** Resume/unlock on a valid user gesture. LIVE: resume + silent-buffer unlock.
 *  MOBILE: just make sure the element + spectrum exist (playback starts on the
 *  player toggle, which is itself a gesture). Never auto-starts music. */
export function userGesture(): void {
  ensureAudio();
  if (audioMode() === "PRECOMPUTED_MOBILE") return;
  if (!graph) return;
  unlock();
  telemetry.audioState = graph.ctx.state;
}

function notifyPlaying(on: boolean): void {
  if (playingTarget === on) {
    // still (re)arm the internal driver if needed (e.g. mobile 'playing' repeat)
    if (on && !externalDriver && !internalRaf) startInternal();
    return;
  }
  playingTarget = on;
  telemetry.playing = on;
  playListeners.forEach((cb) => cb(on));
  if (on && !externalDriver) startInternal();
}

/** Pause: keep the position (no restart on resume). */
export function pausePlayback(): void {
  if (audioMode() === "PRECOMPUTED_MOBILE") {
    mediaEl?.pause();
    return;
  }
  wantPlay = false;
  reconcile();
}

/** ON/OFF toggle used by the player control. Runs inside the click gesture. */
export function togglePlayback(): void {
  if (audioMode() === "PRECOMPUTED_MOBILE") {
    const el = ensureMediaEl();
    loadSpectrum();
    if (!el) return;
    if (el.paused) {
      el.volume = VOLUME;
      const p = el.play();
      // Optimistic ON so the UI flips immediately; the 'play'/'pause' listeners
      // reconcile with reality (iOS rejects only outside a gesture — we're in one).
      notifyPlaying(true);
      if (p && typeof p.then === "function") {
        p.then(() => {
          telemetry.mediaError = "";
        }).catch((err: unknown) => {
          telemetry.mediaError = String(
            (err as { name?: string })?.name || err,
          );
          notifyPlaying(false);
        });
      }
    } else {
      el.pause();
    }
    return;
  }
  ensureLiveGraph();
  if (!graph) return;
  autoplayOnce = false; // user is now in explicit control
  unlock();
  wantPlay = !isPlaying();
  reconcile();
}

/** Exactly one audible source ever. */
export function isPlaying(): boolean {
  if (audioMode() === "PRECOMPUTED_MOBILE")
    return !!mediaEl && !mediaEl.paused;
  return !!(graph && graph.source);
}

/** Subscribe to play-state changes (for React `playing`). Returns unsubscribe. */
export function subscribePlaying(cb: (p: boolean) => void): () => void {
  playListeners.add(cb);
  return () => playListeners.delete(cb);
}

/** The Monogram loop claims/releases the single rAF driver. */
export function setExternalDriver(on: boolean): void {
  externalDriver = on;
  if (on) stopInternal();
  else if (playingTarget || env > 0.001) startInternal();
}

// --- MIXER filter amount setters (desktop) ----------------------------------
function applyHp(amount: number, jump = false): void {
  hpAmount = clamp01(amount);
  if (!graph) return;
  const f = HP_FREQ_MIN * Math.pow(HP_FREQ_MAX / HP_FREQ_MIN, hpAmount);
  const now = graph.ctx.currentTime;
  if (jump) graph.hp.frequency.setValueAtTime(f, now);
  else graph.hp.frequency.setTargetAtTime(f, now, FILTER_TAU);
}
function applyLp(amount: number, jump = false): void {
  lpAmount = clamp01(amount);
  if (!graph) return;
  const f = LP_FREQ_MAX * Math.pow(LP_FREQ_MIN / LP_FREQ_MAX, lpAmount);
  const now = graph.ctx.currentTime;
  if (jump) graph.lp.frequency.setValueAtTime(f, now);
  else graph.lp.frequency.setTargetAtTime(f, now, FILTER_TAU);
}
/** MIXER: set the normalized high-pass amount (0 = neutral/off .. 1 = max). */
export function setHpAmount(amount: number): void {
  applyHp(amount);
}
/** MIXER: set the normalized low-pass amount (0 = neutral/off .. 1 = max). */
export function setLpAmount(amount: number): void {
  applyLp(amount);
}

// --- HEAT gate (desktop) ----------------------------------------------------
/** Home gate for the scroll-driven Heat FX. The Home cue calls this true on mount
 *  and false on unmount, so Heat only engages on a PLAYING Home and ramps fully dry
 *  everywhere else (route leave included). No-op on mobile (no Web Audio graph). */
export function setHeatEnabled(on: boolean): void {
  heatEnabled = on;
}
/** Future Scratch hook: force Heat to dry (smoothly) while a scratch is active,
 *  then restore the scroll-derived amount when released. INERT until a Scratch
 *  implementation calls it — it is never triggered by the current code paths. */
export function setHeatSuppressed(on: boolean): void {
  heatSuppressed = on;
}

/** Smoothed bands already scaled by the fade envelope (0 when silent/paused). */
export function getBands(): { bass: number; mid: number; high: number } {
  return {
    bass: bands.bass * env,
    mid: bands.mid * env,
    high: bands.high * env,
  };
}

/** Reused array of the spatially-blended band energies (0..1, low freq -> high,
 *  NOT env-scaled; the shader applies the fade). Feeds the continuous field. */
export function getHeatmap(): Float32Array {
  return hmField;
}
/** Play/pause fade envelope (0..1) — the heatmap uses it for fade in/out. */
export function getEnv(): number {
  return env;
}

// ============================================================================
//  Per-frame update (shared)
// ============================================================================

/**
 * Build the spectral heatmap. LIVE fills hmRaw from the AnalyserNode FFT
 * (log-mapped bands); MOBILE copies the interpolated precomputed bands into
 * hmRaw. Both then share gate + adaptive normalization + perceptual curve +
 * per-band viscous attack/release + a spatial gaussian blur, so no single band
 * is recognisable. Everything writes into pre-allocated arrays.
 */
function computeHeatmap(dtMs: number, running: boolean): void {
  const dt = dtMs / 1000;
  const mobile = audioMode() === "PRECOMPUTED_MOBILE";
  const active =
    running &&
    EFFECTS.ENABLE_DESKTOP_SPECTRAL_HEATMAP &&
    typeof window !== "undefined" &&
    (mobile
      ? !!spectrum // mobile: no width gate, data-driven (no AudioContext)
      : window.innerWidth >= HEATMAP.minWidthPx && !!graph);
  telemetry.hmActive = active && env > 0.01;

  if (active) {
    let framePeak = 0;
    if (mobile) {
      // Precomputed bands are already dB-normalised (0..1); copy straight in.
      for (let i = 0; i < HM_N; i++) {
        const raw = mBands[i];
        hmRaw[i] = raw;
        if (raw > framePeak) framePeak = raw;
      }
    } else {
      const freq = graph!.freq;
      const bins = freq.length;
      const loBin = Math.max(1, Math.floor(HEATMAP.loBinFrac * bins));
      const hiBin = Math.min(bins - 1, Math.floor(HEATMAP.hiBinFrac * bins));
      const ratio = hiBin / loBin;
      for (let i = 0; i < HM_N; i++) {
        const b0 = Math.floor(loBin * Math.pow(ratio, i / HM_N));
        const b1 = Math.max(
          b0 + 1,
          Math.floor(loBin * Math.pow(ratio, (i + 1) / HM_N)),
        );
        let s = 0;
        for (let b = b0; b < b1; b++) s += freq[b];
        const raw = s / (b1 - b0) / 255;
        if (raw > framePeak) framePeak = raw;
        hmRaw[i] = raw;
      }
    }
    hmNorm = Math.max(framePeak, hmNorm * HEATMAP.normDecay);
    if (hmNorm < HEATMAP.normFloor) hmNorm = HEATMAP.normFloor;
    const g = HEATMAP.noiseGate;
    const divisor = hmNorm * HEATMAP.normHeadroom;
    for (let i = 0; i < HM_N; i++) {
      const raw = hmRaw[i];
      const norm = Math.min(1, raw / divisor);
      const gated = norm < g ? 0 : (norm - g) / (1 - g);
      const target = Math.pow(gated, HEATMAP.perceptualExp);
      const cur = hmSmooth[i];
      const aRate =
        i < HM_N * 0.25 ? HEATMAP.attackRateBass : HEATMAP.attackRate;
      if (target >= cur) {
        hmSmooth[i] = cur + (target - cur) * (1 - Math.exp(-aRate * dt));
      } else {
        hmSmooth[i] =
          cur + (target - cur) * (1 - Math.exp(-HEATMAP.releaseRate * dt));
      }
    }
  } else {
    // Decay smoothly to zero (no FFT / no data read).
    for (let i = 0; i < HM_N; i++)
      hmSmooth[i] +=
        (0 - hmSmooth[i]) * (1 - Math.exp(-HEATMAP.releaseRate * dt));
  }

  spatialBlur();
}

/** Gaussian blur across bands (radius by smoothing level) so adjacent bands melt
 *  into a continuous field — no recognisable columns. Also fills telemetry. */
function spatialBlur(): void {
  const r = HEATMAP.smoothRadius[HEATMAP.smoothing] ?? 4;
  const sigma = Math.max(0.5, r);
  let peak = 0;
  for (let i = 0; i < HM_N; i++) {
    let acc = 0;
    let wsum = 0;
    for (let k = -r; k <= r; k++) {
      const j = i + k;
      if (j < 0 || j >= HM_N) continue;
      const w = Math.exp(-(k * k) / (2 * sigma * sigma));
      acc += hmSmooth[j] * w;
      wsum += w;
    }
    const v = wsum > 0 ? acc / wsum : 0;
    hmField[i] = v;
    if (v > peak) peak = v;
  }
  const grp = (a: number, b: number) => {
    let s = 0;
    const i0 = Math.floor(a * HM_N);
    const i1 = Math.max(i0 + 1, Math.floor(b * HM_N));
    for (let i = i0; i < i1; i++) s += hmField[i];
    return s / (i1 - i0);
  };
  telemetry.hmSub = grp(0, 0.12);
  telemetry.hmBass = grp(0.12, 0.32);
  telemetry.hmMid = grp(0.32, 0.62);
  telemetry.hmHigh = grp(0.62, 1);
  telemetry.hmPeak = peak;
  telemetry.hmBands = HM_N;
}

function avgRange(a: Uint8Array<ArrayBuffer>, from: number, to: number): number {
  let s = 0;
  const lo = Math.max(0, Math.floor(a.length * from));
  const hi = Math.min(a.length, Math.ceil(a.length * to));
  for (let i = lo; i < hi; i++) s += a[i];
  return hi > lo ? s / (hi - lo) / 255 : 0;
}

function smoothTo(cur: number, target: number, dt: number): number {
  const rate = target > cur ? PULSE.attackRate : PULSE.releaseRate;
  return cur + (target - cur) * (1 - Math.exp(-rate * dt));
}

/**
 * raw (0..1) -> adaptive-normalized -> noise-gated -> perceptual curve. Returns
 * [normalized, curved]; also advances the per-band peak.
 */
function shape(raw: number, band: "bass" | "mid" | "high"): [number, number] {
  peaks[band] = Math.max(raw, peaks[band] * PULSE.peakDecay);
  if (peaks[band] < PULSE.peakFloor) peaks[band] = PULSE.peakFloor;
  const norm = Math.min(1, raw / peaks[band]);
  const gated =
    norm < PULSE.noiseGate ? 0 : (norm - PULSE.noiseGate) / (1 - PULSE.noiseGate);
  return [norm, Math.pow(gated, PULSE.perceptualExp)];
}

function writeOut(barEnabled: boolean): void {
  const bp = isMobile() ? PULSE.mobile : PULSE.desktop;
  const level = bands.bass * 0.65 + bands.mid * 0.35;
  const bar = barEnabled
    ? Math.min(1, level * env * (bp.intensity / 2.5) * bp.barGain)
    : 0;
  document.documentElement.style.setProperty("--pulse-bar", bar.toFixed(3));
  telemetry.bass = bands.bass * env;
  telemetry.mid = bands.mid * env;
  telemetry.high = bands.high * env;
  telemetry.pulseStrength = level * env;
  // FINAL applied strength = base level scaled by the per-breakpoint intensity
  // relative to the 2.5 reference (so the +25% mobile boost is reflected here).
  telemetry.sonicFinal = barEnabled ? level * env * (bp.intensity / 2.5) : 0;
  telemetry.sonicIntensity = bp.intensity;
}

function zeroOut(): void {
  bands.bass = bands.mid = bands.high = 0;
  env = 0;
  document.documentElement.style.setProperty("--pulse-bar", "0");
  telemetry.bass = telemetry.mid = telemetry.high = 0;
  telemetry.rawBass = telemetry.rawMid = telemetry.rawHigh = 0;
  telemetry.normBass = telemetry.normMid = telemetry.normHigh = 0;
  telemetry.pulseStrength = 0;
}

/** Write the live media/analysis telemetry each frame (debug panel only). */
function writeModeTelemetry(): void {
  telemetry.mode = audioMode();
  if (audioMode() === "PRECOMPUTED_MOBILE") {
    telemetry.audioState = "media"; // NOT an AudioContext — playback is DIRECT_HTML_MEDIA
    if (mediaEl) {
      telemetry.mediaPaused = mediaEl.paused;
      telemetry.mediaMuted = mediaEl.muted;
      telemetry.mediaVolume = mediaEl.volume;
      telemetry.mediaCurrentTime = mediaEl.currentTime || 0;
      telemetry.mediaDuration = mediaEl.duration || 0;
      telemetry.mediaReadyState = mediaEl.readyState;
    }
    telemetry.mBass = mBMH.bass;
    telemetry.mMid = mBMH.mid;
    telemetry.mHigh = mBMH.high;
    telemetry.mRms = mBMH.rms;
    telemetry.mPeak = mBMH.peak;
    telemetry.audioSourceCount = mediaEl && !mediaEl.paused ? 1 : 0;
  } else if (graph) {
    telemetry.audioState = graph.ctx.state;
    telemetry.audioSourceCount = graph.source ? 1 : 0;
    telemetry.audioOffset = currentOffset();
  }
}

/**
 * Per-frame update. Called by the Monogram loop (external driver) or the
 * internal rAF. dtSec is real elapsed time so everything is frame-rate
 * independent. Cheap no-op when both features are disabled.
 */
export function tick(dtSec: number): void {
  const wantPulse = EFFECTS.ENABLE_SONIC_PULSE;
  const wantHeatmap = EFFECTS.ENABLE_DESKTOP_SPECTRAL_HEATMAP;
  if (!wantPulse && !wantHeatmap) {
    if (env !== 0 || bands.bass !== 0) zeroOut();
    updateHeat(false); // keep Heat ramping to dry even when reactive data is off
    computeHeatmap(0, false); // settle heatmap to zero
    return;
  }
  const dt = Math.min(0.05, Math.max(0, dtSec));
  const mobile = audioMode() === "PRECOMPUTED_MOBILE";

  // "running" requires a live audible source (LIVE) or a playing media element
  // with data + a loaded spectrum (MOBILE), so the reactive data is only read
  // while the track is truly playing.
  let running: boolean;
  if (mobile) {
    running = sampleMobile(); // fills mBands/mBMH when true
  } else {
    running = !!graph && graph.ctx.state === "running" && !!graph.source;
  }
  writeModeTelemetry();
  updateHeat(running); // scroll-driven Heat (desktop); dry unless a playing Home

  const envTarget = playingTarget && running ? 1 : 0;
  const fadeRate = 1000 / (envTarget > env ? PULSE.fadeInMs : PULSE.fadeOutMs);
  env += (envTarget - env) * (1 - Math.exp(-fadeRate * dt));
  if (env < 0.0005) env = envTarget === 0 ? 0 : env;

  if (running) {
    let rawBass: number, rawMid: number, rawHigh: number;
    if (mobile) {
      rawBass = mBMH.bass;
      rawMid = mBMH.mid;
      rawHigh = mBMH.high;
    } else {
      graph!.analyser.getByteFrequencyData(graph!.freq); // ONE FFT read, shared
      rawBass = avgRange(graph!.freq, 0, 0.08);
      rawMid = avgRange(graph!.freq, 0.08, 0.35);
      rawHigh = avgRange(graph!.freq, 0.35, 0.8);
    }
    const [nBass, cBass] = shape(rawBass, "bass");
    const [nMid, cMid] = shape(rawMid, "mid");
    const [nHigh, cHigh] = shape(rawHigh, "high");
    bands.bass = smoothTo(bands.bass, cBass, dt);
    bands.mid = smoothTo(bands.mid, cMid, dt);
    bands.high = smoothTo(bands.high, cHigh, dt);
    telemetry.rawBass = rawBass;
    telemetry.rawMid = rawMid;
    telemetry.rawHigh = rawHigh;
    telemetry.normBass = nBass;
    telemetry.normMid = nMid;
    telemetry.normHigh = nHigh;
  } else {
    bands.bass = smoothTo(bands.bass, 0, dt);
    bands.mid = smoothTo(bands.mid, 0, dt);
    bands.high = smoothTo(bands.high, 0, dt);
  }
  writeOut(wantPulse);
  computeHeatmap(dt * 1000, running);
}

function internalLoop(now: number): void {
  const dt = internalLast ? (now - internalLast) / 1000 : 0.016;
  internalLast = now;
  tick(dt);
  if (!externalDriver && (playingTarget || env > 0.001)) {
    internalRaf = requestAnimationFrame(internalLoop);
  } else {
    internalRaf = 0;
  }
}

function startInternal(): void {
  if (internalRaf || externalDriver) return;
  internalLast = 0;
  internalRaf = requestAnimationFrame(internalLoop);
}

function stopInternal(): void {
  if (internalRaf) cancelAnimationFrame(internalRaf);
  internalRaf = 0;
}
